db:
  host: "postgres:5432"
  name: "bash_db"
  user: "bash_usr"
  password: "bash_pwd"
rest:
  host: ":8080"
  resource-timeout: 5s
  analytics-timeout: 15s
  write-timeout: 15s
  read-timeout: 15s
logger:
  log-file: "logs.log"
  warn-file: "err_logs.log"